import type { Metadata } from "next";
import { Inter, Ubuntu } from "next/font/google";
import "./globals.css";

import CookieConsentOverlay from '@/components/CookieConsentOverlay';
import CookieConsentProvider from '@/providers/CookieConsentProvider';
import GsapProvider from '@/providers/GsapProvider';
import GoogleRecaptchaProvider from '@/providers/GoogleRecaptchaProvider';
import GoogleAnalytics from '@/components/GoogleAnalytics';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SplineProvider from '@/providers/SplineProvider';
import SectionProvider from '@/providers/SectionProvider';

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter',
    display: 'swap'
});
const ubuntu = Ubuntu({
    subsets: ["latin"],
    weight: ['400', '500', '700'],
    variable: '--font-ubuntu',
    display: 'swap'
});

export const metadata: Metadata = {
	title: "Justin Conabree",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`font-sans ${inter.variable} ${ubuntu.variable}`}>
				<CookieConsentProvider>
                    <GoogleAnalytics analyticsId={process.env.GOOGLE_ANALYTICS_ID} />
                    <GoogleRecaptchaProvider recaptchaKey={process.env.RECAPTCHA_SITE_KEY}>
                        <Header />
                        <GsapProvider>
                            <SplineProvider>
                                <SectionProvider>
                                    {children}
                                </SectionProvider>
                            </SplineProvider>
                        </GsapProvider>
                        <Footer />
                    </GoogleRecaptchaProvider>
                    <CookieConsentOverlay />
                </CookieConsentProvider>
                <svg width="0" height="0">
                    <filter id="rgb-split">
                        <feOffset in="SourceGraphic" dx="2" dy="2" result="layer-one" />
                        <feComponentTransfer in="layer-one" result="red">
                            <feFuncR type="identity" />
                            <feFuncG type="discrete" tableValues="0" />
                            <feFuncB type="discrete" tableValues="0" />
                        </feComponentTransfer>

                        <feOffset in="SourceGraphic" dx="-2" dy="-2" result="layer-two" />
                        <feComponentTransfer in="layer-two" result="cyan">
                            <feFuncR type="discrete" tableValues="0" />
                            <feFuncG type="identity" />
                            <feFuncB type="identity" />
                        </feComponentTransfer>

                        <feBlend in="red" in2="cyan" mode="screen" result="color-split" />
                    </filter>
                </svg>
			</body>
		</html>
	);
}
