import type { Metadata } from "next";
import { Inter, Ubuntu } from "next/font/google";
import "./globals.css";

import CookieConsentOverlay from '@/components/CookieConsentOverlay';
import CookieConsentProvider from '@/providers/CookieConsentProvider';
import GsapProvider from '@/providers/GsapProvider';
import GoogleRecaptchaProvider from '@/providers/GoogleRecaptchaProvider';
import GoogleAnalytics from '@/components/GoogleAnalytics';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SplineProvider from '@/providers/SplineProvider';
import SectionProvider from '@/providers/SectionProvider';

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter',
    display: 'swap'
});
const ubuntu = Ubuntu({
    subsets: ["latin"],
    weight: ['400', '500', '700'],
    variable: '--font-ubuntu',
    display: 'swap'
});

export const metadata: Metadata = {
	title: "Justin Conabree",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`font-sans ${inter.variable} ${ubuntu.variable}`}>
				<CookieConsentProvider>
                    <GoogleAnalytics analyticsId={process.env.GOOGLE_ANALYTICS_ID} />
                    <GoogleRecaptchaProvider recaptchaKey={process.env.RECAPTCHA_SITE_KEY}>
                        <Header />
                        <GsapProvider>
                            <SplineProvider>
                                <SectionProvider>
                                    {children}
                                </SectionProvider>
                            </SplineProvider>
                        </GsapProvider>
                        <Footer />
                    </GoogleRecaptchaProvider>
                    <CookieConsentOverlay />
                </CookieConsentProvider>
			</body>
		</html>
	);
}
